import { LOG_PATH_, DATA_BASE_CONFIG_TEST_, PATH_DOCUMENT_COMPANY_ } from './config-dev';

// CONFIGURACION DEL PUERTO DE LA APLICACION
export const HOST_NAME = "localhost";//dominio dev.mayasoft.com.co
export const PORT = 3002;

//CONFIGURACION DEL LOG
export const LOG_PATH = LOG_PATH_;
export const LOG_FILE = "axpress";
export const SHOW_FULL_FILE_PATH = false;

// CONFIGURACION DE LA CONEXION A LA BASE DE DATOS
export const DATA_BASE_CONFIG_TEST = DATA_BASE_CONFIG_TEST_;

// RUTA PARA GUARDAR LOS DOCUMENTOS QUE ADJUNTAN LAS PERSONAS JURIDICAS
export const PATH_DOCUMENT_COMPANY = PATH_DOCUMENT_COMPANY_;

export const FORMATO_FECHA = "dddd, D [de] MMMM [del] YYYY";